#  Copyright 2018 Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /dG9tbXltYWx2ZWVrYXJ3Yg.html
  script: main.app

- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

- url: /(.*)
  static_files: third_party/OpenCV/\1
  upload: third_party/OpenCV/(.*)

- url: /(.*)
  static_files: js/\1
  upload: js/(.*)

- url: /bWFsdmVla2F0b21teWh0bWw/(.*)
  static_files: www/bWFsdmVla2F0b21teWh0bWw/(.*)
  upload: www/bWFsdmVla2F0b21teWh0bWw/(.*)

libraries:
  - name: PIL
    version: latest

  - name: flask
    version: latest
